mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
# from .views import login_view, logout_view,
from .views import (
    set_cookie_view,
    get_cookie_view,
    get_session_view,
    set_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UsersListView,
    AvatarUpdateView,
    UserDetailView,
    HelloView,
)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("avatar-update/<int:pk>/", AvatarUpdateView.as_view(), name="avatar-update"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UsersListView.as_view(), name="users"),
    path("user-details/<int:pk>/", UserDetailView.as_view(), name="user-details"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include("django.contrib.admindocs.urls")),
    path('admin/', admin.site.urls),

    path('blog/', include("BlogApp.urls")),
    path("req/", include("requestdataapp.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include("myapiapp.urls")),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

urlpatterns += i18n_patterns(
    path("accounts/", include("myauth.urls")),
    path("shop/", include("shopapp.urls")),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter
from .views import (
    OrdersListView,
    OrderCreateView,
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsExportView,
    OrdersExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,
    UserOrdersExportView,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("ordrers", OrderViewSet)

urlpatterns = [
    # path("", cache_page(180)(ShopIndexView.as_view()), name="index"),
    path("", ShopIndexView.as_view(), name="index"),

    path("api/", include(routers.urls)),
    path("users/<int:pk>/orders/", UserOrdersListView.as_view(), name="users_orders"),
    path("users/<int:pk>/orders/export/", UserOrdersExportView.as_view(), name="users_orders_export"),

    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/export/", ProductsExportView.as_view(), name="products_export"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="order_list"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/export/", OrdersExportView.as_view(), name="order_export"),
    path("orders/<int:pk>/", OrdersDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete", OrderDeleteView.as_view(), name="order_delete"),
    path("products/latest/feed", LatestProductsFeed(), name="products-feed"),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


def product_preview_dir_path(instance: "Product", filename: str):
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Model Product can be sold

    Orders here: :model:`shopapp.Order`
    """

    class Meta:
        ordering = ["name"]
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="products", null=True)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_dir_path)

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})


def product_images_dir_path(instance: "ProductImages", filename: str):
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_dir_path)
    description = models.TextField(max_length=200, null=False, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to="orders/receipts")

mysite/shopapp/views.py
"""
View func for shop.

For products, orders, ...
"""
from timeit import default_timer
from django.contrib.auth.models import Group, User
from django.contrib.syndication.views import Feed
from django.core.cache import cache
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from rest_framework.parsers import MultiPartParser
from rest_framework.response import Response
from yaml import serialize

from .common import save_csv_products
from .forms import ProductForm, GroupForm
from .models import Product, Order, ProductImages
from .serializers import ProductSerializer, OrderSerializer
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
import logging
from rest_framework.decorators import action
from rest_framework.request import Request
from csv import DictWriter

log = logging.getLogger(__name__)

class UserOrdersExportView(View):
    def get(self, request: HttpRequest, pk):
        cache_key = f"{pk}_user_orders_data_cache"
        orders_data = cache.get(cache_key)
        user = get_object_or_404(User, pk=pk)
        if orders_data is None:
            orders = Order.objects.filter(user=user)

            orders_data = [
                {
                    "pk": order.pk,
                    "delivery_address": order.delivery_address,
                    "created_at": order.created_at,
                }
                for order in orders
            ]
            cache.set(cache_key, orders_data, 300)

        return JsonResponse({"user_id": user.pk, "orders": orders_data})


class UserOrdersListView(ListView):
    template_name = "shopapp/users_orders_list.html"
    def get_queryset(self):
        user_id = self.kwargs.get("pk")

        self.owner = get_object_or_404(User, pk=user_id)

        return Order.objects.filter(user=self.owner)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["owner"] = self.owner
        return context


class LatestProductsFeed(Feed):
    title = "Products (latest)"
    description = 'Update of changes and additions products'
    link = reverse_lazy("shopapp:products_list")

    def items(self):
        return (
            Product.objects
            .order_by("-name")[:5]
        )

    def item_title(self, item):
        return item.name

    def item_description(self, item):
        return item.description[:100]


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter,
    ]

    search_fields = [
        "delivery_address",
        "user",
        "products",
    ]
    ordering_fields = [
        "delivery_address",
        "user",
    ]

@extend_schema(description="Products Views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Set View for change Product
    Same info
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]

    filterset_fields = [
        "name",
        "price",
        "description",
        "discount",
        "archived",
    ]
    search_fields = [
        "name",
        "description",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]
    @method_decorator(cache_page(120))
    def list(self, *args, **kwargs):
        # print("HELLO PRODUCT LIST")
        return super().list(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_cdv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Contrnt-Disposition"] = f"attachment; filename = {filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "price",
            "description",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })

        return response

    @action(
        methods=["post"],
        detail=False,
        parser_classes=[MultiPartParser],
    )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)

    @extend_schema(
        summary="Get one product by id",
        description="Retrieves **product**, return 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response, product by id not found")
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)


class ShopIndexView(View):
    def get(self, request: HttpRequest):
        products = [
            ('Laptop', 1999),
            ("Desktop", 5999),
            ("Phone", 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
            "items": 12,
        }
        log.debug("Products for shop index: %s", products)
        log.info("Rendering shop index")
        print("shop index context", context)
        return render(request, "shopapp/shop_index.html", context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest):
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related("permissions").all(),
        }
        return render(request, "shopapp/groups_list.html", context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = "shopapp/product_details.html"
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"


class ProductsListView(ListView):
    template_name = "shopapp/products_list.html"
    # model = Product
    context_object_name = "products"
    queryset = Product.objects.select_related("user")

class ProductCreateView(PermissionRequiredMixin, CreateView):
    # def test_func(self):
    #     # return self.request.user.groups. filter(name="secret-group").exists()
    #     return self.request.user.is_superuser

    permission_required = "shopapp.add_product"
    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()

        return super().form_valid(form)



class ProductUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_superuser:
            return True
        else:
            self.object = self.get_object()
            has_edit_perm = self.request.user.has_perm("shopapp.change_product")
            created_by_current_user = self.object.user == self.request.user
            return has_edit_perm and created_by_current_user

    model = Product
    # fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        for img in form.files.getlist("images"):
            ProductImages.objects.create(
                product=self.object,
                image=img
            )
        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.success_url
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )


class OrdersDetailView(PermissionRequiredMixin, DetailView):
    permission_required = ["shopapp.view_order", ]
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )


class OrderCreateView(CreateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    success_url = reverse_lazy("shopapp:order_list")


class OrderUpdateView(UpdateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Base title
      {% endblock %}
    </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

<div>
  {% now "H:i" %}
</div>

<div>
  {% now "l" as current_weekday %}
  Today is {{ current_weekday }}
</div>

</body>
</html>

mysite/shopapp/templates/shopapp/create_product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product!</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups_list.html
{% extends "shopapp/base.html" %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        {% if not groups %}
            <h3>No groups yet!</h3>
        {% else %}
            <ul>
                {% for group in groups %}
                    <li>
                        <div>{{ group.name }}</div>
                        <ul>
                            {% for perm in group.permissions.all %}
                                <li>
                                    {{ perm.name }}
                                    (<code>{{ perm.codename }}</code>)
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends "shopapp/base.html" %}

{% block title %}
    Confirm delete order #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to delete order #{{ object.pk }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">
      Back to order
    </a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends "shopapp/base.html" %}

{% block title %}
    Orders List
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">
            Details #{{ order.pk }}</a></p>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: {{ order.promocode }}</p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>Order:</div>
          <ul>
            {% for prod in order.products.all %}
            <li>
              {{ prod.name }} for ${{ prod.price }}
            </li>
            {% endfor %}
          </ul>
        </div>
      {% endfor %}
    </div>
  {% else %}
  <h3>No orders yet!</h3>
  {% endif %}

<div>
  <a href="{% url 'shopapp:order_create' %}">
    Create a new order!
  </a>
</div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Update order
{% endblock %}

{% block body %}
  <h1>Update order!</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">
      Back to order #{{ object.pk }}!
    </a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends "admin/change_list.html" %}


{% block object-tools-items %}
{% load admin_urls %}
  <li>
    <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
      Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends "shopapp/base.html" %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to archive {{ object.name }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}">
      Back to product
    </a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Archive</button>
    </form>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_details.html
{% extends "shopapp/base.html" %}

{% load i18n %}

{% block title %}
    {% translate "Product" %} #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>{% translate "Product" %} <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% translate "Description" %}: <em>{{ product.description }}</em></div>
        <div>{% translate "Price" %}: {{ product.price }}</div>
        <div>{% translate "Discount" %}: {{ product.discount }}</div>
        <div>{% translate "Archived" %}: {{ product.archived }}</div>
        <div>{% translate "Created by" %}: {{ product.user }}</div>
        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
        <div>
        {% blocktranslate count images_count=product.images.all|length %}
            There is only one image.
            {% plural %}
            There are {{ images_count }} images.
        {% endblocktranslate %}
        </div>
        <h3>{% translate "Images" %}:</h3>
        <div>
            {% for img in product.images.all %}
            <div>
                <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                <div>{{ img.description }}</div>
            </div>
            {% empty %}
                <div>{% translate "No images upload yet" %}</div>
            {% endfor %}
        </div>

    </div>

    {% url 'shopapp:product_update' pk=product.pk as update_product_url %}
    {% url 'shopapp:product_delete' pk=product.pk as archived_product_url %}
    {% url 'shopapp:products_list' as product_list_url %}
    {% blocktranslate %}
    <div>
        <a href="{{ update_product_url }}">Update product!</a>
    </div>

    <div>
        <a href="{{ archived_product_url }}">Archive product!</a>
    </div>

    <div>
        <a href="{{ product_list_url }}">Back to products list!</a>
    </div>
    {% endblocktranslate %}

{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
  <h1>Create product</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">
      Back to products list!
    </a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends "admin/change_list.html" %}


{% block object-tools-items %}
{% load admin_urls %}
  <li>
    <a href="{% url 'admin:import_products_csv' %}" class="addlink">
      Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/products_list.html
{% extends "shopapp/base.html" %}

{% load i18n %}

{% block title %}
    {% translate "Products List" %}
{% endblock %}

{% block body %}
  <h1>{% translate "Products" %}:</h1>
  {% if products %}
    <div>
    {% blocktranslate count products_count=products|length %}
      There is only one product.
      {% plural %}
      There are {{ products_count }} products.
    {% endblocktranslate %}
    </div>
    <div>
      {% for product in products %}
        <div>
          <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">
            {% translate "Name" context "product name" %}: {{ product.name }}</a></p>
          <p>{% translate "Price" %}: {{ product.price }}</p>
          {% translate "No discount" as no_discount %}
          <p>{% translate "Discount" %}: {% firstof product.discount no_discount %}</p>
          {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
          {% endif %}
        </div>
      {% endfor %}
    </div>

    {% if perms.shopapp.add_product %}
      <div>
        <a href="{% url 'shopapp:product_create' %}">
          {% translate "Create a new product" %}!
        </a>
      </div>
    {% endif %}

  {% else %}
    {% url 'shopapp:product_create' as create_product_url %}
    {% blocktranslate %}
      <h3>No products yet!</h3>
      <a href="{{ create_product_url }}"
      >Create a new one!</a>
    {% endblocktranslate %}
  {% endif %}



{% endblock %}

mysite/shopapp/templates/shopapp/shop_index.html
{% extends "shopapp/base.html" %}
{% load cache %}

{% block title %}
    Shop index
{% endblock %}

{% block body %}
    <h1>
        Hello shop index!
    </h1>

    <div>
        <ul>
            {% for name, money in products %}
                <li>{{ name|upper }}({{ name|length }}) for ${{ money }}</li>
                {% if name|length > 5 %}
                    <span>Lucky!</span>
                {% endif %}


            {% empty %}
                NO items
            {% endfor %}
        </ul>
    </div>

    <div>
        <strong>
            You have {{ items }} item{{ items|pluralize }}
        </strong>
    </div>
    <div>
        <strong>
            You have {{ items }} class{{ items|pluralize:"es" }}
        </strong>
    </div>
    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
        </strong>
    </div>



    <div>
        Time running: {{ time_running }}
    </div>

    {% cache 100 lorem %}
    <div>
        {% lorem 3 p random %}
    </div>
    {% endcache %}

{% endblock %}

mysite/shopapp/templates/shopapp/users_orders_list.html
{% extends "shopapp/base.html" %}
{% load cache %}

{% block title %}
    User Orders List
{% endblock %}

{% block body %}
<h1>User orders {{ owner.username }}</h1>
{% if object_list %}
    {% cache 120 userorders owner.username %}
    <ul>
        {% for order in object_list %}
        <li>Order {{ order.pk }} - {{ order.created_at }}</li>
        {% endfor %}
    </ul>
    {% endcache %}
{% else %}
    <div>User {{ owner.username }} has no orders yet!</div>
{% endif %}

<div>
    <a href="{% url 'shopapp:order_create' %}">
    Create a new order!
    </a>
</div>

<div>
    <a href="{% url 'shopapp:order_list' %}">
      Back to orders list!
    </a>
</div>

{% endblock %}