mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
# from .views import login_view, logout_view,
from .views import (
    set_cookie_view,
    get_cookie_view,
    get_session_view,
    set_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UsersListView,
    AvatarUpdateView,
    UserDetailView,
    HelloView,
)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("avatar-update/<int:pk>/", AvatarUpdateView.as_view(), name="avatar-update"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UsersListView.as_view(), name="users"),
    path("user-details/<int:pk>/", UserDetailView.as_view(), name="user-details"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include("django.contrib.admindocs.urls")),
    path('admin/', admin.site.urls),

    path('blog/', include("BlogApp.urls")),
    path("req/", include("requestdataapp.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include("myapiapp.urls")),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

urlpatterns += i18n_patterns(
    path("accounts/", include("myauth.urls")),
    path("shop/", include("shopapp.urls")),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models

def profile_avatar_dir_path(instance: "Profile", filename: str):
    return "profile/user_{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=profile_avatar_dir_path, default="uploads/avatars/default.jpg")

    def __str__(self):
        return self.user.name

mysite/myauth/forms.py
from django import forms
from myauth.models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("avatar", )

mysite/myauth/views.py
from random import random

from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.utils.translation import gettext_lazy as _, ngettext
from .forms import ProfileForm
from .models import Profile


class HelloView(View):
    welcome_message = _("Welcome, Hello world!")

    def get(self, request: HttpRequest):
        items_str = request.GET.get("items") or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)

        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)

        return response


class AboutMeView(UpdateView):
    template_name = "myauth/about_me.html"
    model = Profile
    fields = ("avatar",)

    success_url = reverse_lazy("myauth:about-me")

    def get_object(self, queryset=None):
        return self.request.user.profile


# class ChangeAvatarView(UserPassesTestMixin, LoginRequiredMixin, View):
#     def test_func(self):
#         return self.request.user.is_staff or (self.get_object().user == self.request.user)
#
#
#     def get(self, request: HttpRequest, *args, **kwargs):
#         profile = request.user.profile
#         avatar_url = profile.avatar.url if profile.avatar else "static/uploads/avatars/default.jpg"
#         context = {
#             "form": ProfileForm(instance=profile),
#             "avatar": avatar_url,
#         }
#         return render(request, "myauth/update_avatar.html", context=context)
#
#     def post(self, request: HttpRequest, *args, **kwargs):
#         profile = request.user.profile
#         form = ProfileForm(request.POST, request.FILES, instance=profile)
#         if form.is_valid():
#             form.save()
#             return redirect("myauth:about-me")
#
#         avatar_url = profile.avatar.url if profile.avatar else "static/uploads/avatars/default.jpg"
#         context = {
#             "form": ProfileForm(instance=profile),
#             "avatar": avatar_url,
#         }
#         return render(request, "myauth/update_avatar.html", context=context )

class AvatarUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        return self.request.user.is_staff or (self.get_object().user == self.request.user)

    model = Profile
    template_name = "myauth/update_avatar.html"
    form_class = ProfileForm

    def get_success_url(self):
        return reverse("myauth:users")


class UserDetailView(DetailView):
    template_name = "myauth/user_details.html"
    queryset = User.objects.select_related("profile")
    context_object_name = "user"


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect("/admin/")
        return render(request, "myauth/login.html")

    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)

    if user:
        login(request, user)
        return redirect("/admin/")

    return render(request, "myauth/login.html", {"error": "Invalid login or password"})


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse("myauth:login"))


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response

@cache_page(120)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})


class UsersListView(ListView):
    template_name = "myauth/user_list.html"
    context_object_name = "user_list"
    queryset = User.objects.all()

mysite/myauth/templates/myauth/about_me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
    About Me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    <div>
        Products available: {% now "u" %}
    </div>
    {% if user.is_authenticated %}
        {% cache 300 userinfo user.username %}
        <h2>Detail</h2>
        {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" width="200px" height="200px">
        {% else %}
            <div>No avatar yet</div>
        {% endif %}
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
        {% endcache %}
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update avatar</button>
        </form>
    </div>

    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}


{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Login</button>
</form>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/update_avatar.html
{% extends "myauth/base.html" %}

 {% block title %}
    Update avatar
{% endblock %}

{% block body %}
    <h1>User avatar</h1>
    <div>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
      </form>
    </div>
    <div>
      <a href="{% url 'myauth:about-me' %}">
        Back
      </a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/user_details.html
{% extends 'myauth/base.html' %}

{% block title %}
    User info
{% endblock %}

{% block body %}
    <h1>User info</h1>
        <h2>Detail</h2>
        {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" width="200px" height="200px">
        {% else %}
            <div>No avatar yet</div>
        {% endif %}
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>

    <div>
        {% if perms.user.is_stuff %}
            <a href="{% url 'myauth:avatar-update' pk=user.pk %}">Update avatar</a>
        {% endif %}
    </div>

    <div>
      <a href="{% url 'myauth:users' %}">Back to users list</a>
    </div>


{% endblock %}

mysite/myauth/templates/myauth/user_list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h1>Users list</h1>
    {% if user_list %}
        <div>
        {% for user in user_list %}
            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" width="200px" height="200px">
            {% else %}
                <div>No avatar yet</div>
            {% endif %}
            <p>
                Username: <a href=" {% url 'myauth:user-details' pk=user.pk %} ">{{ user.username }}</a>
            </p>

        {% endfor %}
        </div>

    {% else %}
        <div>No users yet!</div>
    {% endif %}

{% endblock %}